"""
Artifact generation: turns a notebook's source content into a saved .md file.

Required artifacts (per assignment spec):
  - Report: summarizes/synthesizes the notebook's sources
  - Quiz:   multiple-choice/short-answer questions WITH an answer key

Both are generated by prompting the LLM with a broad sample of the
notebook's chunk content, then saved to disk via storage.store.save_artifact
so they persist across restarts and can be viewed/downloaded from the UI.
"""

from __future__ import annotations

from pathlib import Path

from . import llm_client
from . import rag_engine
from .storage import store


REPORT_SYSTEM_PROMPT = """You are an analyst producing a clear, well-organized written report
based only on the provided source material. Structure your report in Markdown with:
- A title (H1)
- A short executive summary
- 3-6 thematic sections (H2) covering the key points, facts, and ideas in the material
- A brief conclusion
Do not invent information that isn't supported by the source material. Be concise but thorough."""

QUIZ_SYSTEM_PROMPT = """You are an instructor creating a study quiz based only on the provided
source material. Produce a Markdown document with:
- A title (H1): "Quiz: <topic>"
- 8-10 questions, a mix of multiple-choice (4 options, labeled A-D) and short-answer questions,
  numbered sequentially
- A "## Answer Key" section at the end listing the correct answer (and a one-sentence
  explanation) for every question number
Base every question strictly on the provided material."""


def generate_report(notebook_id: str) -> Path:
    content = rag_engine.get_all_chunks_text(notebook_id)
    if not content.strip():
        raise ValueError("This notebook has no ingested sources yet, so a report can't be generated.")
    notebook_name = store.get_meta(notebook_id)["name"]
    user_prompt = f"Notebook: {notebook_name}\n\nSource material:\n\n{content}"
    report_md = llm_client.generate(REPORT_SYSTEM_PROMPT, user_prompt, max_tokens=2500)
    return store.save_artifact(notebook_id, "report", report_md)


def generate_quiz(notebook_id: str) -> Path:
    content = rag_engine.get_all_chunks_text(notebook_id)
    if not content.strip():
        raise ValueError("This notebook has no ingested sources yet, so a quiz can't be generated.")
    notebook_name = store.get_meta(notebook_id)["name"]
    user_prompt = f"Notebook: {notebook_name}\n\nSource material:\n\n{content}"
    quiz_md = llm_client.generate(QUIZ_SYSTEM_PROMPT, user_prompt, max_tokens=2500)
    return store.save_artifact(notebook_id, "quiz", quiz_md)


ARTIFACT_GENERATORS = {
    "report": generate_report,
    "quiz": generate_quiz,
}
